### ISSUE TITLE
Wrong link in email

### ISSUE THREAD

**Issue by cowingtonpost1** [sjcbulldog/xerodb#10]
The link in the email needs to be HTTPS and it needs to only contain one slash after the domain for it to work.

The link I was sent was `http://www.xerorobot.org:8001//users/confirm/` but it needed to be `https://www.xerorobot.org:8001/users/confirm/`

**Comment by sjcbulldog** [comment]
This has been fixed.  It was just the wrong path in the .env configuration file.
