### ISSUE TITLE
Ease of returning to home (minor)

### ISSUE THREAD

**Issue by sockmagician** [sjcbulldog/xerodb#9]
When you are in a page, for instance a manufactured part, if you want to return to the build database page you have to go all the way back to 'robots'- having a hierarchical back button of sorts would be nice to avoid monotonous clicking to navigate through the database 
![image](https://github.com/sjcbulldog/xerodb/assets/99516554/ed995385-7b96-417d-a67b-df3c0b9e936f)

**Comment by sjcbulldog** [comment]
If you press update it should take you back to the robot build page.  If you just hit the back button in the browser it should do the same.  Are you looking for a back button to make this more clear?  This makes sense and would make it more clear.  I will add this but let me know if this i not what you were thinking.

**Comment by sjcbulldog** [comment]
I have added a back button that will take you back to the hierarchical robot view without updating the current part.  Let me know if this is not what you had in mind.

**Comment by sockmagician** [comment]
Awesome, sounds great. I’ll check it out when I get homeThank you,Aasha PatelOn Sep 10, 2023, at 8:43 AM, sjcbulldog ***@***.***> wrote:﻿
Closed #9 as completed.
